export const en = {
  navbar: {
    home: "Home",
    services: "Services",
    products: "Products",
    about: "About",
    contact: "Contact Us",
    contactShort: "Contact",
    darkMode: "Dark mode"
  },
  introduction: {
    headingPrefix: "We build your projects with ",
    words: [
      "artificial intelligence",
      "automation",
      "innovation",
      "technology"
    ],
    subheading: "AI solutions designed to scale your business.",
    ctaContact: "Contact Us",
    ctaFreeTrial: "Free Trial"
  },
  services: {
    sectionTag: "Capabilities",
    sectionTitle: "Corporate ",
    sectionTitleHighlight: "services",
    items: [
      {
        title: "Sites",
        tagline: "Landing Pages & E-Commerce"
      },
      {
        title: "Flows",
        tagline: "Automations"
      },
      {
        title: "Bots",
        tagline: "Conversational AI"
      },
      {
        title: "Stock",
        tagline: "ERP Systems"
      },
      {
        title: "Dev",
        tagline: "Custom Systems"
      }
    ]
  },
  products: {
    sectionTag: "Portfolio",
    sectionTitle: "Featured ",
    sectionTitleHighlight: "projects",
    scrollText: "Keep scrolling",
    deliveryDetails: "Delivery details:",
    items: [
      {
        title: "Tumy Sites",
        tagline: "Case Study: Aetherium Web Portal",
        description: "Development of a high-performance corporate website for a global SaaS platform. Optimized for SEO, featuring ultra-fast loading speed and interactive design in Next.js.",
        features: ["Integrated automated technical SEO", "Dynamically generated persuasive copy", "99/100 load speed in Lighthouse"]
      },
      {
        title: "Tumy Commerce",
        tagline: "Case Study: Aethel Luxury Store",
        description: "Minimalist and luxury online store designed for an interior design firm. Integrates international payments, predictive inventory management, and automated shipping control.",
        features: ["Ultra-fast interactive shopping cart", "Configured Stripe and PayPal gateways", "Automatic minimum stock projection"]
      },
      {
        title: "Tumy Bots",
        tagline: "Case Study: Aether AI Agent",
        description: "Conversational virtual assistant trained with a corporation's customer care manual. Handles technical inquiries and processes support requests 24/7.",
        features: ["Accurate responses without hallucinations", "Integration with WhatsApp and Instagram channels", "Automatic escalation to human agents"]
      },
      {
        title: "Tumy Analytics",
        tagline: "Case Study: Dataflex Dashboard",
        description: "Financial monitoring and analysis web dashboard. Translates charts of sales, user retention, and costs into understandable text reports generated by AI.",
        features: ["Metric explanation in natural language", "Automatic revenue anomaly alerts", "One-click executive report export"]
      }
    ]
  },
  about: {
    sectionTag: "About us",
    sectionTitle: "From an idea ",
    sectionTitleHighlight: "to a mission",
    paragraphs: [
      "Tumy.ai was born from the conviction that technology should be accessible to all companies.",
      "We combine artificial intelligence with custom development to deliver real results, not generic templates.",
      "From Peru, we connect with companies across Latin America, transforming their operations with cutting-edge technology."
    ],
    valuesTag: "Values",
    valuesTitle: "What ",
    valuesTitleHighlight: "defines us",
    valuesItems: [
      {
        title: "Precision",
        description: "Each solution solves specific and measurable business problems. We do not build generic developments."
      },
      {
        title: "Innovation",
        description: "We implement the latest technologies in conversational AI and automation to always keep you one step ahead."
      },
      {
        title: "Collaboration",
        description: "We work hand-in-hand with your technical and business teams from initial prototyping to final launch."
      }
    ]
  },
  advantages: {
    revealText: "We transform ideas into digital solutions with artificial intelligence",
    sectionTag: "Why choose us",
    sectionTitle: "Advantages ",
    sectionTitleHighlight: "of working with us",
    items: [
      { titulo: "Unique Design", texto: "No generic templates." },
      { titulo: "Total Security", texto: "Guaranteed stability." },
      { titulo: "Flexibility", texto: "Adapted to your needs." },
      { titulo: "Smart Investment", texto: "Long-term cost reduction." },
      { titulo: "Dedicated Support", texto: "Constant support." }
    ]
  },
  team: {
    sectionTag: "Team",
    sectionTitle: "Experts ",
    sectionTitleHighlight: "in development",
    sectionSub: "Computer Science students at UTEC, Lima, Peru.",
    items: [
      {
        name: "Adrian Auqui Perez",
        role: "Full-Stack Developer & AI Engineer",
        bio: "Specialist in AI, Three.js, and software architecture. Passionate about compilers and data structures."
      },
      {
        name: "Fabrizzio Vilchez",
        role: "Full-Stack Developer & DevOps",
        bio: "Full-stack developer with 4+ years of experience. Focused on cloud computing, ML, and IoT systems."
      }
    ]
  },
  contact: {
    sectionTag: "Contact",
    sectionTitle: "Contact Us",
    sectionSub: "We are here to help you. Write to us through any of these means.",
    formTitle: "Send us a message",
    formNamePlaceholder: "Name",
    formEmailPlaceholder: "Email address",
    formMessagePlaceholder: "How can we help you?",
    formSubmit: "Send message",
    formSubmitting: "Sending...",
    formSuccess: "Message sent successfully. We will get in touch with you.",
    formError: "Error sending message. Please try again.",
    socialTitle: "Social media",
    validationName: "Name is required",
    validationEmailRequired: "Email is required",
    validationEmailInvalid: "Invalid email address",
    validationMessageRequired: "Message is required",
    validationMessageMin: "Minimum 10 characters"
  },
  cta: {
    sectionTag: "Digital Transformation",
    sectionTitle: "Next level",
    sectionSub: "Schedule a free strategic session with our AI engineering team. We design custom solutions integrating intelligent agents, automation flows, and interactive experiences tailored to your business model.",
    button: "Schedule free consultation"
  },
  footer: {
    tagline: "AI solutions to transform your business.",
    colCompany: "Company",
    colLegal: "Legal",
    colSocial: "Social",
    terms: "Terms of service",
    privacy: "Privacy",
    cookies: "Cookies",
    rights: "All rights reserved."
  }
};
