export const en = {
  navbar: {
    home: "Home",
    services: "Services",
    products: "Products",
    about: "About",
    contact: "Contact Us",
    contactShort: "Contact",
    darkMode: "Dark mode"
  },
  introduction: {
    headingPrefix: "We build your projects with ",
    words: [
      "artificial intelligence",
      "automation",
      "innovation",
      "technology"
    ],
    subheading: "AI solutions designed to scale your business.",
    ctaContact: "Contact Us",
    ctaFreeTrial: "Free Trial"
  },
  services: {
    sectionTag: "Capabilities",
    sectionTitle: "Corporate ",
    sectionTitleHighlight: "services",
    items: [
      {
        title: "Sites",
        tagline: "Landing Pages & E-Commerce"
      },
      {
        title: "Flows",
        tagline: "Automations"
      },
      {
        title: "Bots",
        tagline: "Conversational AI"
      },
      {
        title: "Stock",
        tagline: "ERP Systems"
      },
      {
        title: "Dev",
        tagline: "Custom Systems"
      }
    ]
  },
  products: {
    sectionTag: "Portfolio",
    sectionTitle: "Featured ",
    sectionTitleHighlight: "projects",
    scrollText: "Keep scrolling",
    deliveryDetails: "Delivery details:",
    visitLink: "Visit site ↗",
    items: [
      {
        title: "MAC Lima",
        tagline: "Case Study: Museum Management Portal",
        description: "Comprehensive management and cataloging system for the Museum of Contemporary Art in Lima. Enables digital administration of collections, artworks, donors, heritage, and institutional access control with Google Workspace.",
        features: ["Digital cataloging of artworks & artists", "Donation management and tracking", "Granular role-based access control"]
      },
      {
        title: "Tumy Sites",
        tagline: "Case Study: Aetherium Web Portal",
        description: "Development of a high-performance corporate website for a global SaaS platform. Optimized for SEO, featuring ultra-fast loading speed and interactive design in Next.js.",
        features: ["Integrated automated technical SEO", "Dynamically generated persuasive copy", "99/100 load speed in Lighthouse"]
      },
      {
        title: "Tumy Commerce",
        tagline: "Case Study: Aethel Luxury Store",
        description: "Minimalist and luxury online store designed for an interior design firm. Integrates international payments, predictive inventory management, and automated shipping control.",
        features: ["Ultra-fast interactive shopping cart", "Configured Stripe and PayPal gateways", "Automatic minimum stock projection"]
      },
      {
        title: "Tumy Bots",
        tagline: "Case Study: Aether AI Agent",
        description: "Conversational virtual assistant trained with a corporation's customer care manual. Handles technical inquiries and processes support requests 24/7.",
        features: ["Accurate responses without hallucinations", "Integration with WhatsApp and Instagram channels", "Automatic escalation to human agents"]
      },
      {
        title: "Tumy Analytics",
        tagline: "Case Study: Dataflex Dashboard",
        description: "Financial monitoring and analysis web dashboard. Translates charts of sales, user retention, and costs into understandable text reports generated by AI.",
        features: ["Metric explanation in natural language", "Automatic revenue anomaly alerts", "One-click executive report export"]
      }
    ]
  },
  about: {
    sectionTag: "About us",
    sectionTitle: "From an idea ",
    sectionTitleHighlight: "to a mission",
    paragraphs: [
      "Tumy.ai was born from the conviction that technology should be accessible to all companies.",
      "We combine artificial intelligence with custom development to deliver real results, not generic templates.",
      "From Peru, we connect with companies across Latin America, transforming their operations with cutting-edge technology."
    ],
    valuesTag: "Values",
    valuesTitle: "What ",
    valuesTitleHighlight: "defines us",
    valuesItems: [
      {
        title: "Precision",
        description: "Each solution solves specific and measurable business problems. We do not build generic developments."
      },
      {
        title: "Innovation",
        description: "We implement the latest technologies in conversational AI and automation to always keep you one step ahead."
      },
      {
        title: "Collaboration",
        description: "We work hand-in-hand with your technical and business teams from initial prototyping to final launch."
      }
    ]
  },
  advantages: {
    revealText: "We transform ideas into digital solutions with artificial intelligence",
    sectionTag: "Why choose us",
    sectionTitle: "Advantages ",
    sectionTitleHighlight: "of working with us",
    items: [
      { titulo: "Unique Design", texto: "No generic templates." },
      { titulo: "Total Security", texto: "Guaranteed stability." },
      { titulo: "Flexibility", texto: "Adapted to your needs." },
      { titulo: "Smart Investment", texto: "Long-term cost reduction." },
      { titulo: "Dedicated Support", texto: "Constant support." }
    ]
  },
  team: {
    sectionTag: "Team",
    sectionTitle: "Experts ",
    sectionTitleHighlight: "in development",
    sectionSub: "Computer Science students at UTEC, Lima, Peru.",
    items: [
      {
        name: "Adrian Auqui Perez",
        role: "Full-Stack Developer & AI Engineer",
        bio: "Specialist in AI, Three.js, and software architecture. Passionate about compilers and data structures."
      },
      {
        name: "Fabrizzio Vilchez",
        role: "Full-Stack Developer & DevOps",
        bio: "Full-stack developer with 4+ years of experience. Focused on cloud computing, ML, and IoT systems."
      }
    ]
  },
  contact: {
    sectionTag: "Contact",
    sectionTitle: "Contact Us",
    sectionSub: "We are here to help you. Write to us through any of these means.",
    formTitle: "Send us a message",
    formNamePlaceholder: "Name",
    formEmailPlaceholder: "Email address",
    formMessagePlaceholder: "How can we help you?",
    formSubmit: "Send message",
    formSubmitting: "Sending...",
    formSuccess: "Message sent successfully. We will get in touch with you.",
    formError: "Error sending message. Please try again.",
    socialTitle: "Social media",
    validationName: "Name is required",
    validationEmailRequired: "Email is required",
    validationEmailInvalid: "Invalid email address",
    validationMessageRequired: "Message is required",
    validationMessageMin: "Minimum 10 characters"
  },
  cta: {
    sectionTag: "Digital Transformation",
    sectionTitle: "Next level",
    sectionSub: "Schedule a free strategic session with our AI engineering team. We design custom solutions integrating intelligent agents, automation flows, and interactive experiences tailored to your business model.",
    button: "Schedule free consultation"
  },
  footer: {
    tagline: "AI solutions to transform your business.",
    colCompany: "Company",
    colLegal: "Legal",
    colSocial: "Social",
    terms: "Terms of service",
    privacy: "Privacy",
    cookies: "Cookies",
    rights: "All rights reserved."
  },
  notFound: {
    title: "404 - Route Not Found",
    subtitle: "The system has detected an anomaly: the requested path does not exist on this server.",
    recoveryProtocol: "Recovery protocol initiated.",
    analyzingRequest: "Analyzing request...",
    routeError: "ERROR: 404_PAGE_NOT_FOUND",
    recommendation: "Recommendation: Return to a safe zone.",
    commandPrompt: "guest@tumy.ai:~$ cd /home",
    button: "Execute home.sh"
  },
  cookieBanner: {
    message: "We use essential cookies to improve your experience and analyze site traffic. By continuing to browse, you agree to our cookie policy.",
    accept: "Accept",
    decline: "Decline"
  },
  cookiesPage: {
    title: "Cookie Policy",
    subtitle: "Information about how we use cookies on our website.",
    intro: "At Tumy.ai, we value your privacy. This policy details what cookies we use and for what purposes.",
    typesTitle: "Cookies We Use",
    essentialTitle: "1. Essential Cookies",
    essentialDesc: "These cookies are necessary for the website to function and cannot be deactivated in our systems since they store your preferences.",
    tableHeaders: ["Name", "Purpose", "Duration"],
    cookiesList: [
      { name: "lang / NEXT_LOCALE", purpose: "Stores your selected language preference (Spanish or English).", duration: "1 year" },
      { name: "cookie-consent", purpose: "Stores your decision regarding the acceptance or rejection of our cookie policy.", duration: "1 year" },
      { name: "theme", purpose: "Stores your preference for the interface's visual theme (Light or Dark).", duration: "Persistent" },
      { name: "_ga, _ga_*", purpose: "Google Analytics: Tracks anonymous usage statistics, visits, and behavior to improve the service.", duration: "Up to 2 years" }
    ],
    manageTitle: "Manage Your Preferences",
    manageDesc: "You can reset your cookie settings at any time using the button below. This will clear your records and make the consent banner reappear.",
    resetButton: "Reset Cookie Preferences",
    resetSuccess: "Preferences reset successfully. Reloading page...",
    backButton: "Back to Home"
  },
  termsPage: {
    legalTag: "[ LEGAL ]",
    title: "Terms of Service",
    lastUpdated: "Last updated: ",
    sections: [
      {
        title: "1. Acceptance of terms",
        content: "By accessing and using the Tumy.ai website, you agree to be bound by these Terms of Service and all applicable laws and regulations. If you do not agree with any of these terms, you are prohibited from using or accessing this site.",
        list: []
      },
      {
        title: "2. Use License",
        content: "Permission is granted to temporarily interact with the materials on the Tumy.ai website for personal, non-commercial transitory viewing or corporate evaluation purposes only. Under this license you may not:",
        list: [
          "Modify or copy the design materials and visual identity entirely.",
          "Attempt to decompile or reverse engineer any software contained on the website.",
          "Remove any copyright or other proprietary notations from the materials."
        ]
      },
      {
        title: "3. Disclaimer",
        content: "The materials on the Tumy.ai website are provided on an 'as is' basis. Tumy.ai makes no warranties, expressed or implied, and hereby disclaims and negates all other warranties including, without limitation, implied warranties or conditions of merchantability, fitness for a particular purpose.",
        list: []
      },
      {
        title: "4. Limitations",
        content: "In no event shall Tumy.ai or its suppliers be liable for any damages arising out of the use or inability to use the materials or services on the site, even if Tumy.ai or an authorized representative has been notified orally or in writing of the possibility of such damage.",
        list: []
      },
      {
        title: "5. Revisions",
        content: "Tumy.ai may revise these terms of service for its website at any time without notice. By using this website you are agreeing to be bound by the then current version of these Terms of Service.",
        list: []
      }
    ]
  },
  privacyPage: {
    legalTag: "[ LEGAL ]",
    title: "Privacy Policy",
    lastUpdated: "Last updated: ",
    sections: [
      {
        title: "1. Information we collect",
        content: "At Tumy.ai, we collect personal information that you voluntarily provide to us, such as your name, email address, and company details when using our contact form or requesting our services.",
        list: []
      },
      {
        title: "2. Use of information",
        content: "We use the collected information to:",
        list: [
          "Provide, operate, and maintain our services.",
          "Improve and personalize user experience.",
          "Understand and analyze how you use our platform.",
          "Communicate with you for customer service and promotional purposes."
        ]
      },
      {
        title: "3. Data protection",
        content: "We implement a variety of high-level security measures to maintain the safety of your personal information when you place a request or access our services. We do not share your information with third parties without your consent, except when required by law.",
        list: []
      },
      {
        title: "4. Third-party services",
        content: "This site is protected by Google reCAPTCHA to prevent spam and abuse. The use of reCAPTCHA is subject to the Google <a href=\"https://policies.google.com/privacy\" target=\"_blank\" rel=\"noopener noreferrer\" class=\"underline hover:text-black dark:hover:text-white transition-colors\">Privacy Policy</a> and <a href=\"https://policies.google.com/terms\" target=\"_blank\" rel=\"noopener noreferrer\" class=\"underline hover:text-black dark:hover:text-white transition-colors\">Terms of Service</a>.",
        list: []
      },
      {
        title: "5. Contact",
        content: "If you have additional questions or require more information about our Privacy Policy, do not hesitate to contact us through our email: <a href=\"mailto:tumy.ai.pe@gmail.com\" class=\"underline hover:text-black dark:hover:text-white transition-colors\">tumy.ai.pe@gmail.com</a>.",
        list: []
      }
    ]
  },
  whatsapp: {
    ariaLabel: "Chat with us on WhatsApp",
    text: "Chat with us"
  }
};
